Added info to the readme about udev rules file
HalosGhost/enlighten pull request #7
Opened 2017-10-30 19:28 UTC by meskarune

I added some instructions so people can setup the udev rules if they want.

2017-10-30 20:07 UTC, HalosGhost requested changes
You won't be able to copy the rules to ``/etc`` as a regular user. The ``install`` make target already handles it anyway.

2017-10-31 00:12 UTC, meskarune commented
Oh I see, so people just need to add themselves to the "video" group to have permission?

2017-10-31 05:21 UTC, HalosGhost commented
@meskarune, that's right, yeah.

2017-11-01 16:53 UTC, HalosGhost approved these changes

2017-11-01 16:53 UTC, merged